import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <meta name='carbon-collective' content="CARB-72" />
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
